"""One-shot script to backfill `example` field on existing words without it."""
import json
from pathlib import Path

DATA_PATH = Path(__file__).resolve().parent.parent / "data" / "words.json"

EX = {}

def e(wid, en, es, sr, sr_cyr, ar, ar_translit):
    EX[wid] = {"en": en, "es": es, "sr": sr, "sr_cyr": sr_cyr, "ar": ar, "ar_translit": ar_translit}

# Greetings, pronouns, questions, basic verbs (w002-w019)
e("w002", "Yes, please.", "Sí, por favor.", "Da, molim.", "Да, молим.", "نعم، من فضلك.", "naʿam, min faḍlik")
e("w003", "No, thank you.", "No, gracias.", "Ne, hvala.", "Не, хвала.", "لا، شكراً.", "lā, shukran")
e("w004", "Thank you very much.", "Muchas gracias.", "Hvala puno.", "Хвала пуно.", "شكراً جزيلاً.", "shukran jazīlan")
e("w005", "Water, please.", "Agua, por favor.", "Vodu, molim.", "Воду, молим.", "ماء، من فضلك.", "māʾ, min faḍlik")
e("w006", "I am here.", "Yo estoy aquí.", "Ja sam ovde.", "Ја сам овде.", "أنا هنا.", "anā hunā")
e("w007", "You are kind.", "Tú eres amable.", "Ti si ljubazan.", "Ти си љубазан.", "أنتَ لطيف.", "anta laṭīf")
e("w008", "He is here.", "Él está aquí.", "On je ovde.", "Он је овде.", "هو هنا.", "huwa hunā")
e("w009", "She is happy.", "Ella está feliz.", "Ona je srećna.", "Она је срећна.", "هي سعيدة.", "hiya saʿīda")
e("w010", "We are friends.", "Nosotros somos amigos.", "Mi smo prijatelji.", "Ми смо пријатељи.", "نحن أصدقاء.", "naḥnu aṣdiqāʾ")
e("w011", "What is this?", "¿Qué es esto?", "Šta je ovo?", "Шта је ово?", "ما هذا؟", "mā hādhā?")
e("w012", "Where is the house?", "¿Dónde está la casa?", "Gde je kuća?", "Где је кућа?", "أين البيت؟", "ayna al-bayt?")
e("w013", "When do you come?", "¿Cuándo vienes?", "Kada dolaziš?", "Када долазиш?", "متى تأتي؟", "matā taʾtī?")
e("w014", "Who is this?", "¿Quién es?", "Ko je ovo?", "Ко је ово?", "من هذا؟", "man hādhā?")
e("w015", "How are you?", "¿Cómo estás?", "Kako si?", "Како си?", "كيف حالك؟", "kayfa ḥāluk?")
e("w016", "Why not?", "¿Por qué no?", "Zašto ne?", "Зашто не?", "لماذا لا؟", "limādhā lā?")
e("w017", "I want coffee.", "Quiero café.", "Želim kafu.", "Желим кафу.", "أريد قهوة.", "urīdu qahwa")
e("w018", "I go to school.", "Voy a la escuela.", "Idem u školu.", "Идем у школу.", "أذهب إلى المدرسة.", "adhhabu ilā al-madrasa")
e("w019", "I eat bread.", "Como pan.", "Jedem hleb.", "Једем хлеб.", "آكل الخبز.", "ākulu al-khubz")

# Food, home, time, numbers, people, qualities (w021-w030)
e("w021", "Good food.", "Buena comida.", "Dobra hrana.", "Добра храна.", "طعام جيد.", "ṭaʿām jayyid")
e("w022", "My house is here.", "Mi casa está aquí.", "Moja kuća je ovde.", "Моја кућа је овде.", "بيتي هنا.", "baytī hunā")
e("w023", "A nice day.", "Un día agradable.", "Lep dan.", "Леп дан.", "يوم جميل.", "yawm jamīl")
e("w024", "Today is Monday.", "Hoy es lunes.", "Danas je ponedeljak.", "Данас је понедељак.", "اليوم الإثنين.", "al-yawm al-ithnayn")
e("w025", "One coffee, please.", "Un café, por favor.", "Jednu kafu, molim.", "Једну кафу, молим.", "قهوة واحدة، من فضلك.", "qahwa wāḥida, min faḍlik")
e("w026", "Two days.", "Dos días.", "Dva dana.", "Два дана.", "يومان.", "yawmān")
e("w027", "My name is Sara.", "Mi nombre es Sara.", "Moje ime je Sara.", "Моје име је Сара.", "اسمي سارة.", "ismī sāra")
e("w028", "A good person.", "Una buena persona.", "Dobra osoba.", "Добра особа.", "شخص جيد.", "shakhṣ jayyid")
e("w029", "Good morning.", "Buenos días.", "Dobro jutro.", "Добро јутро.", "صباح الخير.", "ṣabāḥ al-khayr")
e("w030", "A new book.", "Un libro nuevo.", "Nova knjiga.", "Нова књига.", "كتاب جديد.", "kitāb jadīd")

# Greetings + pronouns + questions extensions (w031-w043)
e("w031", "Goodbye, see you tomorrow.", "Adiós, hasta mañana.", "Doviđenja, vidimo se sutra.", "Довиђења, видимо се сутра.", "مع السلامة، إلى الغد.", "maʿa al-salāma, ilā al-ghad")
e("w032", "Good morning, friend.", "Buenos días, amigo.", "Dobro jutro, prijatelju.", "Добро јутро, пријатељу.", "صباح الخير، يا صديقي.", "ṣabāḥ al-khayr, yā ṣadīqī")
e("w033", "Good evening, everyone.", "Buenas tardes, a todos.", "Dobro veče, svima.", "Добро вече, свима.", "مساء الخير، للجميع.", "masāʾ al-khayr, lil-jamīʿ")
e("w034", "I'm sorry, I'm late.", "Lo siento, llego tarde.", "Izvini, kasnim.", "Извини, касним.", "آسف، أنا متأخر.", "āsif, anā mutaʾakhkhir")
e("w035", "You're very welcome.", "De nada, en serio.", "Nema na čemu, stvarno.", "Нема на чему, стварно.", "عفواً، حقاً.", "ʿafwan, ḥaqqan")
e("w036", "You are all friends.", "Vosotros sois amigos.", "Vi ste prijatelji.", "Ви сте пријатељи.", "أنتم أصدقاء.", "antum aṣdiqāʾ")
e("w037", "They are coming.", "Ellos vienen.", "Oni dolaze.", "Они долазе.", "هم قادمون.", "hum qādimūn")
e("w038", "They are coming.", "Ellas vienen.", "One dolaze.", "Оне долазе.", "هن قادمات.", "hunna qādimāt")
e("w039", "This is good.", "Esto es bueno.", "Ovo je dobro.", "Ово је добро.", "هذا جيد.", "hādhā jayyid")
e("w040", "That is mine.", "Eso es mío.", "To je moje.", "То је моје.", "ذلك لي.", "dhālika lī")
e("w041", "Which one?", "¿Cuál?", "Koji?", "Који?", "أي واحد؟", "ayy wāḥid?")
e("w042", "How much is it?", "¿Cuánto cuesta?", "Koliko košta?", "Колико кошта?", "كم الثمن؟", "kam al-thaman?")
e("w043", "Whose book is this?", "¿De quién es este libro?", "Čija je ova knjiga?", "Чија је ова књига?", "لمن هذا الكتاب؟", "liman hādhā al-kitāb?")

# Numbers 3-100 (w044-w062)
e("w044", "Three children.", "Tres niños.", "Troje dece.", "Троје деце.", "ثلاثة أطفال.", "thalāthat aṭfāl")
e("w045", "Four rooms.", "Cuatro habitaciones.", "Četiri sobe.", "Четири собе.", "أربع غرف.", "arbaʿ ghuraf")
e("w046", "Five fingers.", "Cinco dedos.", "Pet prstiju.", "Пет прстију.", "خمسة أصابع.", "khamsat aṣābiʿ")
e("w047", "Six hours.", "Seis horas.", "Šest sati.", "Шест сати.", "ست ساعات.", "sitt sāʿāt")
e("w048", "Seven days.", "Siete días.", "Sedam dana.", "Седам дана.", "سبعة أيام.", "sabʿat ayyām")
e("w049", "Eight people.", "Ocho personas.", "Osam osoba.", "Осам особа.", "ثمانية أشخاص.", "thamāniyat ashkhāṣ")
e("w050", "Nine books.", "Nueve libros.", "Devet knjiga.", "Девет књига.", "تسعة كتب.", "tisʿat kutub")
e("w051", "Ten minutes.", "Diez minutos.", "Deset minuta.", "Десет минута.", "عشر دقائق.", "ʿashar daqāʾiq")
e("w052", "Eleven cars.", "Once coches.", "Jedanaest auta.", "Једанаест аута.", "أحد عشر سيارة.", "aḥada ʿashar sayyāra")
e("w053", "Twelve months.", "Doce meses.", "Dvanaest meseci.", "Дванаест месеци.", "اثنا عشر شهراً.", "ithnā ʿashar shahran")
e("w054", "Thirteen pages.", "Trece páginas.", "Trinaest strana.", "Тринаест страна.", "ثلاثة عشر صفحة.", "thalāthata ʿashar ṣafḥa")
e("w055", "Fourteen years old.", "Catorce años.", "Četrnaest godina.", "Четрнаест година.", "أربعة عشر سنة.", "arbaʿata ʿashar sana")
e("w056", "Fifteen minutes.", "Quince minutos.", "Petnaest minuta.", "Петнаест минута.", "خمسة عشر دقيقة.", "khamsata ʿashar daqīqa")
e("w057", "Sixteen days.", "Dieciséis días.", "Šesnaest dana.", "Шеснаест дана.", "ستة عشر يوماً.", "sittata ʿashar yawman")
e("w058", "Seventeen books.", "Diecisiete libros.", "Sedamnaest knjiga.", "Седамнаест књига.", "سبعة عشر كتاباً.", "sabʿata ʿashar kitāban")
e("w059", "Eighteen years old.", "Dieciocho años.", "Osamnaest godina.", "Осамнаест година.", "ثمانية عشر سنة.", "thamāniyata ʿashar sana")
e("w060", "Nineteen students.", "Diecinueve estudiantes.", "Devetnaest studenata.", "Деветнаест студената.", "تسعة عشر طالباً.", "tisʿata ʿashar ṭāliban")
e("w061", "Twenty euros.", "Veinte euros.", "Dvadeset evra.", "Двадесет евра.", "عشرون يورو.", "ʿishrūn yūrū")
e("w062", "One hundred years.", "Cien años.", "Sto godina.", "Сто година.", "مئة سنة.", "miʾat sana")

# Time (w063-w082)
e("w063", "Yesterday was sunny.", "Ayer hizo sol.", "Juče je bilo sunčano.", "Јуче је било сунчано.", "أمس كان مشمساً.", "ams kāna mushmisan")
e("w064", "See you tomorrow.", "Hasta mañana.", "Vidimo se sutra.", "Видимо се сутра.", "أراك غداً.", "arāka ghadan")
e("w065", "Come now, please.", "Ven ahora, por favor.", "Dođi sada, molim.", "Дођи сада, молим.", "تعال الآن، من فضلك.", "taʿāl al-ān, min faḍlik")
e("w066", "Beautiful morning.", "Mañana hermosa.", "Lepo jutro.", "Лепо јутро.", "صباح جميل.", "ṣabāḥ jamīl")
e("w067", "In the evening.", "Por la tarde.", "Uveče.", "Увече.", "في المساء.", "fī al-masāʾ")
e("w068", "Good night.", "Buenas noches.", "Laku noć.", "Лаку ноћ.", "تصبح على خير.", "tuṣbiḥ ʿalā khayr")
e("w069", "One hour.", "Una hora.", "Jedan sat.", "Један сат.", "ساعة واحدة.", "sāʿa wāḥida")
e("w070", "Five minutes.", "Cinco minutos.", "Pet minuta.", "Пет минута.", "خمس دقائق.", "khams daqāʾiq")
e("w071", "Next week.", "La próxima semana.", "Sledeće nedelje.", "Следеће недеље.", "الأسبوع القادم.", "al-usbūʿ al-qādim")
e("w072", "Last month.", "El mes pasado.", "Prošli mesec.", "Прошли месец.", "الشهر الماضي.", "al-shahr al-māḍī")
e("w073", "This year.", "Este año.", "Ove godine.", "Ове године.", "هذه السنة.", "hādhihi al-sana")
e("w074", "See you Monday.", "Hasta el lunes.", "Vidimo se u ponedeljak.", "Видимо се у понедељак.", "أراك يوم الإثنين.", "arāka yawm al-ithnayn")
e("w075", "On Tuesday.", "El martes.", "U utorak.", "У уторак.", "يوم الثلاثاء.", "yawm al-thulāthāʾ")
e("w076", "Wednesday morning.", "El miércoles por la mañana.", "Sreda ujutru.", "Среда ујутру.", "صباح الأربعاء.", "ṣabāḥ al-arbiʿāʾ")
e("w077", "Thursday evening.", "El jueves por la tarde.", "Četvrtak uveče.", "Четвртак увече.", "مساء الخميس.", "masāʾ al-khamīs")
e("w078", "Happy Friday.", "Feliz viernes.", "Srećan petak.", "Срећан петак.", "جمعة مباركة.", "jumʿa mubāraka")
e("w079", "On Saturday.", "El sábado.", "U subotu.", "У суботу.", "يوم السبت.", "yawm al-sabt")
e("w080", "Sunday is a rest day.", "El domingo es día de descanso.", "Nedelja je dan odmora.", "Недеља је дан одмора.", "الأحد يوم راحة.", "al-aḥad yawm rāḥa")
e("w081", "I get up early.", "Me levanto temprano.", "Ustajem rano.", "Устајем рано.", "أستيقظ مبكراً.", "astayqiẓ mubakkiran")
e("w082", "I am late.", "Llego tarde.", "Kasnim.", "Касним.", "أنا متأخر.", "anā mutaʾakhkhir")

# Food (w083-w102)
e("w083", "Fresh bread.", "Pan fresco.", "Svež hleb.", "Свеж хлеб.", "خبز طازج.", "khubz ṭāzaj")
e("w084", "Cold milk.", "Leche fría.", "Hladno mleko.", "Хладно млеко.", "حليب بارد.", "ḥalīb bārid")
e("w085", "Black coffee.", "Café negro.", "Crna kafa.", "Црна кафа.", "قهوة سوداء.", "qahwa sawdāʾ")
e("w086", "Tea with sugar.", "Té con azúcar.", "Čaj sa šećerom.", "Чај са шећером.", "شاي مع السكر.", "shāy maʿa al-sukkar")
e("w087", "Red meat.", "Carne roja.", "Crveno meso.", "Црвено месо.", "لحم أحمر.", "laḥm aḥmar")
e("w088", "Roasted chicken.", "Pollo asado.", "Pečena piletina.", "Печена пилетина.", "دجاج مشوي.", "dajāj mashwī")
e("w089", "Fresh fish.", "Pescado fresco.", "Sveža riba.", "Свежа риба.", "سمك طازج.", "samak ṭāzaj")
e("w090", "White rice.", "Arroz blanco.", "Beli pirinač.", "Бели пиринач.", "أرز أبيض.", "aruz abyaḍ")
e("w091", "Sweet fruit.", "Fruta dulce.", "Slatko voće.", "Слатко воће.", "فاكهة حلوة.", "fākiha ḥilwa")
e("w092", "Fresh vegetables.", "Verdura fresca.", "Sveže povrće.", "Свеже поврће.", "خضار طازج.", "khuḍār ṭāzaj")
e("w093", "Red apple.", "Manzana roja.", "Crvena jabuka.", "Црвена јабука.", "تفاحة حمراء.", "tuffāḥa ḥamrāʾ")
e("w094", "Yellow banana.", "Plátano amarillo.", "Žuta banana.", "Жута банана.", "موزة صفراء.", "mawza ṣafrāʾ")
e("w095", "Sweet orange.", "Naranja dulce.", "Slatka pomorandža.", "Слатка поморанџа.", "برتقالة حلوة.", "burtuqāla ḥilwa")
e("w096", "Boiled egg.", "Huevo cocido.", "Kuvano jaje.", "Кувано јаје.", "بيضة مسلوقة.", "bayḍa maslūqa")
e("w097", "Yellow cheese.", "Queso amarillo.", "Žuti sir.", "Жути сир.", "جبن أصفر.", "jubn aṣfar")
e("w098", "Sugar in tea.", "Azúcar en el té.", "Šećer u čaju.", "Шећер у чају.", "سكر في الشاي.", "sukkar fī al-shāy")
e("w099", "Pass the salt, please.", "Pasa la sal, por favor.", "Dodaj so, molim.", "Додај со, молим.", "ناولني الملح، من فضلك.", "nāwilnī al-milḥ, min faḍlik")
e("w100", "Good breakfast.", "Buen desayuno.", "Dobar doručak.", "Добар доручак.", "فطور جيد.", "fuṭūr jayyid")
e("w101", "Let's have lunch.", "Almorcemos.", "Hajdemo na ručak.", "Хајдемо на ручак.", "لنتناول الغداء.", "linatanāwal al-ghadāʾ")
e("w102", "Dinner at home.", "Cena en casa.", "Večera kod kuće.", "Вечера код куће.", "العشاء في البيت.", "al-ʿashāʾ fī al-bayt")
e("w103", "I drink water.", "Bebo agua.", "Pijem vodu.", "Пијем воду.", "أشرب الماء.", "ashrabu al-māʾ")

# Home (w104-w124)
e("w104", "A cup of tea.", "Una taza de té.", "Šolja čaja.", "Шоља чаја.", "كوب شاي.", "kūb shāy")
e("w105", "Around the table.", "Alrededor de la mesa.", "Oko stola.", "Око стола.", "حول الطاولة.", "ḥawla al-ṭāwila")
e("w106", "Open the door.", "Abre la puerta.", "Otvori vrata.", "Отвори врата.", "افتح الباب.", "iftaḥ al-bāb")
e("w107", "Close the window.", "Cierra la ventana.", "Zatvori prozor.", "Затвори прозор.", "أغلق النافذة.", "aghliq al-nāfidha")
e("w108", "A clean room.", "Una habitación limpia.", "Čista soba.", "Чиста соба.", "غرفة نظيفة.", "ghurfa naẓīfa")
e("w109", "In the kitchen.", "En la cocina.", "U kuhinji.", "У кухињи.", "في المطبخ.", "fī al-maṭbakh")
e("w110", "Where is the bathroom?", "¿Dónde está el baño?", "Gde je kupatilo?", "Где је купатило?", "أين الحمام؟", "ayna al-ḥammām?")
e("w111", "Soft bed.", "Cama suave.", "Mekan krevet.", "Мекан кревет.", "سرير ناعم.", "sarīr nāʿim")
e("w112", "Two chairs.", "Dos sillas.", "Dve stolice.", "Две столице.", "كرسيان.", "kursiyān")
e("w113", "Turn on the light.", "Enciende la luz.", "Upali svetlo.", "Упали светло.", "أشعل الضوء.", "ashʿil al-ḍawʾ")
e("w114", "Where are my keys?", "¿Dónde están mis llaves?", "Gde su moji ključevi?", "Где су моји кључеви?", "أين مفاتيحي؟", "ayna mafātīḥī?")
e("w115", "My phone is new.", "Mi teléfono es nuevo.", "Moj telefon je nov.", "Мој телефон је нов.", "هاتفي جديد.", "hātifī jadīd")
e("w116", "On the computer.", "En la computadora.", "Na kompjuteru.", "На компјутеру.", "على الحاسوب.", "ʿalā al-ḥāsūb")
e("w117", "I watch TV.", "Veo la televisión.", "Gledam televiziju.", "Гледам телевизију.", "أشاهد التلفاز.", "ushāhid al-tilfāz")
e("w118", "Fast car.", "Coche rápido.", "Brz auto.", "Брз ауто.", "سيارة سريعة.", "sayyāra sarīʿa")
e("w119", "New clothes.", "Ropa nueva.", "Nova odeća.", "Нова одећа.", "ملابس جديدة.", "malābis jadīda")
e("w120", "New shoes.", "Zapatos nuevos.", "Nove cipele.", "Нове ципеле.", "أحذية جديدة.", "aḥdhiya jadīda")
e("w121", "My bag is heavy.", "Mi bolsa es pesada.", "Moja torba je teška.", "Моја торба је тешка.", "حقيبتي ثقيلة.", "ḥaqībatī thaqīla")
e("w122", "I need money.", "Necesito dinero.", "Treba mi novac.", "Треба ми новац.", "أحتاج مالاً.", "aḥtāj mālan")
e("w123", "A blue pen.", "Un bolígrafo azul.", "Plava olovka.", "Плава оловка.", "قلم أزرق.", "qalam azraq")
e("w124", "White paper.", "Papel blanco.", "Beli papir.", "Бели папир.", "ورق أبيض.", "waraq abyaḍ")

# People (w125-w142)
e("w125", "A young man.", "Un hombre joven.", "Mlad čovek.", "Млад човек.", "رجل شاب.", "rajul shābb")
e("w126", "A kind woman.", "Una mujer amable.", "Ljubazna žena.", "Љубазна жена.", "امرأة لطيفة.", "imraʾa laṭīfa")
e("w127", "A small child.", "Un niño pequeño.", "Malo dete.", "Мало дете.", "طفل صغير.", "ṭifl ṣaghīr")
e("w128", "A good boy.", "Un buen chico.", "Dobar dečak.", "Добар дечак.", "ولد جيد.", "walad jayyid")
e("w129", "A smart girl.", "Una chica inteligente.", "Pametna devojčica.", "Паметна девојчица.", "بنت ذكية.", "bint dhakiyya")
e("w130", "My best friend.", "Mi mejor amigo.", "Moj najbolji prijatelj.", "Мој најбољи пријатељ.", "أفضل أصدقائي.", "afḍal aṣdiqāʾī")
e("w131", "My family.", "Mi familia.", "Moja porodica.", "Моја породица.", "عائلتي.", "ʿāʾilatī")
e("w132", "My mother is kind.", "Mi madre es amable.", "Moja majka je ljubazna.", "Моја мајка је љубазна.", "أمي لطيفة.", "ummī laṭīfa")
e("w133", "My father works.", "Mi padre trabaja.", "Moj otac radi.", "Мој отац ради.", "أبي يعمل.", "abī yaʿmal")
e("w134", "My older brother.", "Mi hermano mayor.", "Moj stariji brat.", "Мој старији брат.", "أخي الأكبر.", "akhī al-akbar")
e("w135", "My younger sister.", "Mi hermana menor.", "Moja mlađa sestra.", "Моја млађа сестра.", "أختي الصغرى.", "ukhtī al-ṣughrā")
e("w136", "Their son.", "Su hijo.", "Njihov sin.", "Њихов син.", "ابنهم.", "ibnuhum")
e("w137", "Their daughter.", "Su hija.", "Njihova ćerka.", "Њихова ћерка.", "ابنتهم.", "ibnatuhum")
e("w138", "Her husband.", "Su marido.", "Njen muž.", "Њен муж.", "زوجها.", "zawjuhā")
e("w139", "His wife.", "Su esposa.", "Njegova žena.", "Његова жена.", "زوجته.", "zawjatuhu")
e("w140", "Our teacher is good.", "Nuestro maestro es bueno.", "Naš učitelj je dobar.", "Наш учитељ је добар.", "معلمنا جيد.", "muʿallimunā jayyid")
e("w141", "A new student.", "Un nuevo estudiante.", "Novi student.", "Нови студент.", "طالب جديد.", "ṭālib jadīd")
e("w142", "A good doctor.", "Un buen doctor.", "Dobar lekar.", "Добар лекар.", "طبيب جيد.", "ṭabīb jayyid")

# Verbs (w143-w167)
e("w143", "I have a friend.", "Tengo un amigo.", "Imam prijatelja.", "Имам пријатеља.", "عندي صديق.", "ʿindī ṣadīq")
e("w144", "I work at home.", "Trabajo en casa.", "Radim kod kuće.", "Радим код куће.", "أعمل في البيت.", "aʿmal fī al-bayt")
e("w145", "I sleep eight hours.", "Duermo ocho horas.", "Spavam osam sati.", "Спавам осам сати.", "أنام ثماني ساعات.", "anām thamānī sāʿāt")
e("w146", "I see you.", "Te veo.", "Vidim te.", "Видим те.", "أراك.", "arāka")
e("w147", "I hear music.", "Oigo música.", "Čujem muziku.", "Чујем музику.", "أسمع الموسيقى.", "asmaʿ al-mūsīqā")
e("w148", "I speak Arabic.", "Hablo árabe.", "Govorim arapski.", "Говорим арапски.", "أتكلم العربية.", "atakallam al-ʿarabiyya")
e("w149", "I read a book.", "Leo un libro.", "Čitam knjigu.", "Читам књигу.", "أقرأ كتاباً.", "aqraʾ kitāban")
e("w150", "I write a letter.", "Escribo una carta.", "Pišem pismo.", "Пишем писмо.", "أكتب رسالة.", "aktub risāla")
e("w151", "I learn every day.", "Aprendo cada día.", "Učim svaki dan.", "Учим сваки дан.", "أتعلم كل يوم.", "ataʿallam kull yawm")
e("w152", "I understand you.", "Te entiendo.", "Razumem te.", "Разумем те.", "أفهمك.", "afhamuka")
e("w153", "I know the answer.", "Sé la respuesta.", "Znam odgovor.", "Знам одговор.", "أعرف الإجابة.", "aʿrif al-ijāba")
e("w154", "I think so.", "Eso pienso.", "Tako mislim.", "Тако мислим.", "أعتقد ذلك.", "aʿtaqid dhālika")
e("w155", "I love you.", "Te amo.", "Volim te.", "Волим те.", "أحبك.", "uḥibbuka")
e("w156", "I come tomorrow.", "Vengo mañana.", "Dolazim sutra.", "Долазим сутра.", "آتي غداً.", "ātī ghadan")
e("w157", "I leave at six.", "Salgo a las seis.", "Izlazim u šest.", "Излазим у шест.", "أخرج في الساعة السادسة.", "akhruj fī al-sāʿa al-sādisa")
e("w158", "I buy bread.", "Compro pan.", "Kupujem hleb.", "Купујем хлеб.", "أشتري الخبز.", "ashtarī al-khubz")
e("w159", "I sell my car.", "Vendo mi coche.", "Prodajem auto.", "Продајем ауто.", "أبيع سيارتي.", "abīʿ sayyāratī")
e("w160", "I open the door.", "Abro la puerta.", "Otvaram vrata.", "Отварам врата.", "أفتح الباب.", "aftaḥ al-bāb")
e("w161", "I close the window.", "Cierro la ventana.", "Zatvaram prozor.", "Затварам прозор.", "أغلق النافذة.", "ughliq al-nāfidha")
e("w162", "I sit here.", "Me siento aquí.", "Sedim ovde.", "Седим овде.", "أجلس هنا.", "ajlis hunā")
e("w163", "I help my friend.", "Ayudo a mi amigo.", "Pomažem prijatelju.", "Помажем пријатељу.", "أساعد صديقي.", "usāʿid ṣadīqī")
e("w164", "I need help.", "Necesito ayuda.", "Treba mi pomoć.", "Треба ми помоћ.", "أحتاج المساعدة.", "aḥtāj al-musāʿada")
e("w165", "I can do it.", "Puedo hacerlo.", "Mogu to da uradim.", "Могу то да урадим.", "أستطيع فعل ذلك.", "astaṭīʿ fiʿl dhālika")
e("w166", "I give you a gift.", "Te doy un regalo.", "Dajem ti poklon.", "Дајем ти поклон.", "أعطيك هدية.", "uʿṭīka hadiyya")
e("w167", "I take the bus.", "Tomo el autobús.", "Uzimam autobus.", "Узимам аутобус.", "آخذ الحافلة.", "ākhudh al-ḥāfila")

# Qualities (w168-w182)
e("w168", "Bad day.", "Mal día.", "Loš dan.", "Лош дан.", "يوم سيء.", "yawm sayyiʾ")
e("w169", "Big house.", "Casa grande.", "Velika kuća.", "Велика кућа.", "بيت كبير.", "bayt kabīr")
e("w170", "Small dog.", "Perro pequeño.", "Mali pas.", "Мали пас.", "كلب صغير.", "kalb ṣaghīr")
e("w171", "New car.", "Coche nuevo.", "Nov auto.", "Нов ауто.", "سيارة جديدة.", "sayyāra jadīda")
e("w172", "Old book.", "Libro viejo.", "Stara knjiga.", "Стара књига.", "كتاب قديم.", "kitāb qadīm")
e("w173", "Hot tea.", "Té caliente.", "Vruć čaj.", "Врућ чај.", "شاي حار.", "shāy ḥārr")
e("w174", "Cold water.", "Agua fría.", "Hladna voda.", "Хладна вода.", "ماء بارد.", "māʾ bārid")
e("w175", "A beautiful day.", "Un día hermoso.", "Lep dan.", "Леп дан.", "يوم جميل.", "yawm jamīl")
e("w176", "I am happy.", "Estoy feliz.", "Srećan sam.", "Срећан сам.", "أنا سعيد.", "anā saʿīd")
e("w177", "Don't be sad.", "No estés triste.", "Ne budi tužan.", "Не буди тужан.", "لا تكن حزيناً.", "lā takun ḥazīnan")
e("w178", "Very easy.", "Muy fácil.", "Vrlo lako.", "Врло лако.", "سهل جداً.", "sahl jiddan")
e("w179", "Difficult question.", "Pregunta difícil.", "Teško pitanje.", "Тешко питање.", "سؤال صعب.", "suʾāl ṣaʿb")
e("w180", "Fast runner.", "Corredor rápido.", "Brz trkač.", "Брз тркач.", "عداء سريع.", "ʿaddāʾ sarīʿ")
e("w181", "Slow car.", "Coche lento.", "Spor auto.", "Спор ауто.", "سيارة بطيئة.", "sayyāra baṭīʾa")
e("w182", "Delicious food.", "Comida deliciosa.", "Ukusna hrana.", "Укусна храна.", "طعام لذيذ.", "ṭaʿām ladhīdh")

# Places (w183-w196)
e("w183", "A big city.", "Una ciudad grande.", "Velik grad.", "Велик град.", "مدينة كبيرة.", "madīna kabīra")
e("w184", "Beautiful country.", "País hermoso.", "Lepa zemlja.", "Лепа земља.", "بلد جميل.", "balad jamīl")
e("w185", "I go to school.", "Voy a la escuela.", "Idem u školu.", "Идем у школу.", "أذهب إلى المدرسة.", "adhhabu ilā al-madrasa")
e("w186", "Near the hospital.", "Cerca del hospital.", "Blizu bolnice.", "Близу болнице.", "قريب من المستشفى.", "qarīb min al-mustashfā")
e("w187", "The store is open.", "La tienda está abierta.", "Prodavnica je otvorena.", "Продавница је отворена.", "المتجر مفتوح.", "al-matjar maftūḥ")
e("w188", "Quiet street.", "Calle tranquila.", "Tiha ulica.", "Тиха улица.", "شارع هادئ.", "shāriʿ hādiʾ")
e("w189", "In the park.", "En el parque.", "U parku.", "У парку.", "في الحديقة.", "fī al-ḥadīqa")
e("w190", "At the airport.", "En el aeropuerto.", "Na aerodromu.", "На аеродрому.", "في المطار.", "fī al-maṭār")
e("w191", "I go to the bank.", "Voy al banco.", "Idem u banku.", "Идем у банку.", "أذهب إلى البنك.", "adhhabu ilā al-bank")
e("w192", "At the market.", "En el mercado.", "Na pijaci.", "На пијаци.", "في السوق.", "fī al-sūq")
e("w193", "Near the mosque.", "Cerca de la mezquita.", "Blizu džamije.", "Близу џамије.", "قريب من المسجد.", "qarīb min al-masjid")
e("w194", "Old church.", "Iglesia antigua.", "Stara crkva.", "Стара црква.", "كنيسة قديمة.", "kanīsa qadīma")
e("w195", "At the office.", "En la oficina.", "U kancelariji.", "У канцеларији.", "في المكتب.", "fī al-maktab")
e("w196", "A nice restaurant.", "Un buen restaurante.", "Lep restoran.", "Леп ресторан.", "مطعم جميل.", "maṭʿam jamīl")


def main():
    with open(DATA_PATH, "r", encoding="utf-8") as f:
        data = json.load(f)
    added = 0
    skipped = 0
    missing = []
    for w in data["words"]:
        if "example" in w:
            skipped += 1
            continue
        if w["id"] in EX:
            w["example"] = EX[w["id"]]
            added += 1
        else:
            missing.append(w["id"])
    with open(DATA_PATH, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"Added: {added}, skipped (already had): {skipped}")
    if missing:
        print(f"Still missing examples for {len(missing)} entries: {missing[:10]}...")


if __name__ == "__main__":
    main()
